import simpleGit, { SimpleGit } from 'simple-git';
import type { GitBotConfig } from '../config';
import { logger } from '../logger';

/**
 * Mengubah string sembarang menjadi slug yang aman untuk nama branch Git.
 * Contoh: "Login Test — broken #1" → "login-test-broken-1"
 */
function toSlug(str: string): string {
  return str
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-+|-+$/g, '')
    .slice(0, 50);
}

/**
 * GitService menangani semua operasi Git yang diperlukan untuk Phase 4:
 * - Membuat branch baru dengan format `auto-healing/{slug}-{timestamp}`
 * - Melakukan commit dengan identitas bot
 * - Push branch ke remote origin
 *
 * Menggunakan library `simple-git` secara async.
 */
export class GitService {
  private readonly git: SimpleGit;

  constructor(
    private readonly botConfig: GitBotConfig,
    workDir: string = process.cwd(),
  ) {
    this.git = simpleGit(workDir);
  }

  /**
   * Membuat branch baru, commit file yang sudah di-patch, dan push ke remote.
   *
   * @param testName  - Nama test (dipakai sebagai bagian nama branch)
   * @param filePaths - Daftar path file yang sudah diubah (akan di-stage)
   * @returns         - Nama branch yang dibuat
   */
  async createBranchAndCommit(testName: string, filePaths: string[]): Promise<string> {
    const slug       = toSlug(testName);
    const timestamp  = Date.now();
    const branchName = `auto-healing/${slug}-${timestamp}`;

    logger.info('[git-service] Menyiapkan branch baru', { branchName });

    // Set identitas bot untuk commit ini (lokal, tidak mengubah git config global)
    await this.git.addConfig('user.name',  this.botConfig.name,  false, 'local');
    await this.git.addConfig('user.email', this.botConfig.email, false, 'local');

    // Buat dan pindah ke branch baru
    await this.git.checkoutLocalBranch(branchName);
    logger.info('[git-service] Branch dibuat', { branchName });

    // Stage hanya file yang di-patch
    await this.git.add(filePaths);
    logger.info('[git-service] File di-stage', { files: filePaths });

    // Commit dengan pesan deskriptif
    const commitMessage =
      `chore(self-healing): update locator for "${testName}"\n\n` +
      `Files patched:\n${filePaths.map(f => `  - ${f}`).join('\n')}\n\n` +
      `[auto-generated by self-healing bot]`;

    await this.git.commit(commitMessage);
    logger.info('[git-service] Commit berhasil', { branchName });

    // Push branch ke remote dan set upstream tracking
    await this.git.push('origin', branchName, ['--set-upstream']);
    logger.info('[git-service] Branch berhasil di-push ke remote', { branchName });

    return branchName;
  }
}
